name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run dev &  # Запускає сервер у фоновому режимі

      - name: Wait for server to be ready
        run: sleep 10  # Чекає 10 секунд, щоб сервер запустився

      - name: Run Playwright tests
        run: npm run test:e2e  # Запускає енд-ту-енд тести