name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # Встановлюємо всі залежності

      - name: Install Playwright browsers
        run: npx playwright install  # Завантажуємо браузери для Playwright

      - name: Run e2e tests
        run: npm run test:e2e  # Запуск енд-ту-енд тестів